name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      uses: docker/compose-action@v2.1.1

    - name: Check Docker Compose Version
      run: docker-compose --version
      
    - name: Copy .env.example to .env
      run: cp ./Integ-tests/.env.example ./Integ-tests/.env

    - name: Run integration script
      run: cd Integ-tests && npm run test:integration
